version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres-banco
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: order_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - order-network


networks: 
  order-network:
    driver: bridge
